---
name: ROS 2 Repos Check

on:
  pull_request:
    branches:
      - '*'

jobs:
  format_and_validity:
    name: Format and Validity
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python3 -m pip install vcstool yamllint
      - name: Validate formatting
        run: >
          yamllint ros2.repos
          -f github
          -d "{extends: default, rules: {document-start: {present: false}, key-ordering: {}}}"
      - name: Validate repositories
        run: vcs validate --input ros2.repos

  commit_message_standards:
    name: Space ROS Commit Message Standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: space-ros/check-commit-message-action@main
